server:
  port: 8080
  servlet:
    context-path: /springBoot
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 0ms
        min-idle: 0
file:
  savepath: /home/template
  webpath: http://image.newaigo.com/spoc-musk/upload/
  folderpath: /upload
wx:
  appId: wx6adb38baa5f3a278
  userAppSecret: 50705e5b3e9809ac72d0fa22628f5c13
  mchId: 1547602861
  notify_url: https://shop.ivygate.cn/ws-shop/ws/shop/payment/callBack
  vip_notify_url: https://shop.ivygate.cn/ws-shop/ws/shop/payment/vipCallBack
  pay_sign_type: MD5
  trade_type: JSAPI
  pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
  token_url: https://api.weixin.qq.com/cgi-bin/token
  send_msg_url: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send